

services:
  regression:
    image: python:3.12-alpine
    build:
      shm_size: '2gb'  # Нужно для Chrome (чтобы избежать ошибок с shared memory)
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/workspace
    command: /bin/sh -c "ls -la && pytest -sv --alluredir=allure-results"
    working_dir: /usr/workspace
    environment:
      - LOGIN=${LOGIN}
      - PASSWORD=${PASSWORD}